### PR TITLE
RAY-229 feat: add currency to proerty price

### PR DESCRIPTION
**Pull request by s-eastwood**
Hi @simonf7 and @cdobson 
And same with this one :)

### CODE REVIEW

**Review by simonf7 — COMMENTED** [review]
Looks ok, my only concern is where else the js client might be used as these are a breaking change.

Could you add an optional parameter 'includeCurrency' to trigger the new behaviour, but also maintain backwards compatibility?

**Comment by simonf7** [comment]
> Looks ok, my only concern is where else the js client might be used as these are a breaking change.
> 
> Could you add an optional parameter 'includeCurrency' to trigger the new behaviour, but also maintain backwards compatibility?

@cdobson might have a better idea of where else the client is used and whether this change affects them

**Comment by s-eastwood** [comment]
@simonf7 for TABS its only used in the file react-prototype/src/js/components/screens/properties/PropertyPriceRange.react.js - which is the other PR.
But you are right it could be used by other clients I am not aware of.

**Comment by s-eastwood** [comment]
@simonf7 and @cdobson I've added the new parmater and passed it in from the price range file in the TABS PR

**Review by simonf7 — APPROVED** [review]

**Pull request merged**
